# Generated by Django 6.0.6 on 2026-06-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms_app', '0006_sensor_platform_m_type_s_order_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs_type',
            name='display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
