# Generated by Django 6.0.6 on 2026-07-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms_app', '0007_obs_type_display_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='platformsource',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddConstraint(
            model_name='platformsource',
            constraint=models.UniqueConstraint(fields=('platform_id',), name='unique_platform_source_platform_id'),
        ),
    ]
