# Generated by Django 6.0.6 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platforms_app", "0009_multi_obs_platform_date_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceSensor",
            fields=[
                (
                    "row_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("row_entry_date", models.DateTimeField(blank=True, null=True)),
                ("row_update_date", models.DateTimeField(blank=True, null=True)),
                (
                    "data_source_id",
                    models.ForeignKey(
                        db_column="data_source_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="platforms_app.datasource",
                    ),
                ),
                (
                    "m_type_id",
                    models.ForeignKey(
                        db_column="m_type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="platforms_app.m_type",
                    ),
                ),
            ],
            options={
                "db_table": '"platforms"."data_source_sensor"',
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data_source_id", "m_type_id"),
                        name="uq_data_source_sensor",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlatformSensorDisplay",
            fields=[
                (
                    "row_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("row_entry_date", models.DateTimeField(blank=True, null=True)),
                ("row_update_date", models.DateTimeField(blank=True, null=True)),
                (
                    "display",
                    models.BooleanField(
                        help_text="Overrides the DataSource default for this sensor."
                    ),
                ),
                (
                    "platform_id",
                    models.ForeignKey(
                        db_column="platform_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="platforms_app.platform",
                    ),
                ),
                (
                    "sensor_id",
                    models.ForeignKey(
                        db_column="sensor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="platforms_app.sensor",
                    ),
                ),
            ],
            options={
                "db_table": '"platforms"."platform_sensor_display"',
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform_id", "sensor_id"),
                        name="uq_platform_sensor_display",
                    ),
                ],
            },
        ),
    ]
