# Generated by Django 5.2.14 on 2026-06-01 20:35

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import projects_catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS projects;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"projects"."product_category"',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"projects"."product_types"',
            },
        ),
        migrations.CreateModel(
            name='HostingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_type', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('data_summary', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('product_category', models.ForeignKey(blank=True, db_column='product_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting_locations', to='projects_catalog.productcategory')),
            ],
            options={
                'db_table': '"projects"."hosting_locations"',
            },
        ),
        migrations.CreateModel(
            name='HostingLocationProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosting_location', models.ForeignKey(db_column='hosting_location_id', on_delete=django.db.models.deletion.CASCADE, to='projects_catalog.hostinglocation')),
                ('product_type', models.ForeignKey(db_column='product_type_id', on_delete=django.db.models.deletion.PROTECT, to='projects_catalog.producttype')),
            ],
            options={
                'db_table': '"projects"."hosting_location_product_types"',
            },
        ),
        migrations.AddField(
            model_name='hostinglocation',
            name='product_types',
            field=models.ManyToManyField(related_name='hosting_locations', through='projects_catalog.HostingLocationProductType', to='projects_catalog.producttype'),
        ),
        migrations.CreateModel(
            name='ProjectCatalogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('project_full_title', models.TextField(blank=True, null=True)),
                ('project_lead', models.TextField(blank=True, null=True)),
                ('project_lead_email', models.TextField(blank=True, null=True)),
                ('project_lead_phone', models.TextField(blank=True, null=True)),
                ('neighborhood', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('project_url', models.TextField(blank=True, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_impact', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': '"projects"."project_catalog_pages"',
                'indexes': [models.Index(fields=['geom'], name='idx_project_catalog_pages_geom')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='project_dates_ok')],
            },
        ),
        migrations.AddField(
            model_name='hostinglocation',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='hosting_locations', to='projects_catalog.projectcatalogpage'),
        ),
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('affiliation', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='projects_catalog.projectcatalogpage')),
            ],
            options={
                'db_table': '"projects"."project_partners"',
            },
        ),
        migrations.CreateModel(
            name='ProjectPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('picture_path', models.FileField(blank=True, max_length=512, null=True, upload_to=projects_catalog.models.project_picture_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='projects_catalog.projectcatalogpage')),
            ],
            options={
                'db_table': '"projects"."project_pictures"',
            },
        ),
        migrations.AddIndex(
            model_name='hostinglocationproducttype',
            index=models.Index(fields=['product_type'], name='idx_hlpt_product_type_id'),
        ),
        migrations.AddConstraint(
            model_name='hostinglocationproducttype',
            constraint=models.UniqueConstraint(fields=('hosting_location', 'product_type'), name='hosting_location_product_types_pk'),
        ),
        migrations.AddIndex(
            model_name='hostinglocation',
            index=models.Index(fields=['project'], name='idx_host_locs_project_id'),
        ),
        migrations.AddIndex(
            model_name='projectpartner',
            index=models.Index(fields=['project'], name='idx_proj_partners_project_id'),
        ),
        migrations.AddIndex(
            model_name='projectpicture',
            index=models.Index(fields=['project'], name='idx_proj_pictures_project_id'),
        ),
    ]
