from django.db import IntegrityError, transaction
from django.test import TestCase

from projects_catalog.models import (
    HostingLocation,
    HostingLocationProductType,
    project_picture_upload_to,
)
from projects_catalog.tests.factories import (
    create_hosting_location,
    create_product_type,
    create_project,
    utc_datetime,
)


class ProjectCatalogModelTests(TestCase):
    def test_project_slug_autogenerated_from_name(self):
        project = create_project("River Watch 2026")

        self.assertEqual(project.slug, "river-watch-2026")

    def test_project_slug_autogenerated_is_unique(self):
        first = create_project("Community Mapping")
        second = create_project("Community Mapping")

        self.assertEqual(first.slug, "community-mapping")
        self.assertEqual(second.slug, "community-mapping-2")

    def test_project_slug_preserved_when_explicitly_provided(self):
        project = create_project("My Project", slug="custom-project-slug")

        self.assertEqual(project.slug, "custom-project-slug")

    def test_hosting_location_slug_uses_data_type_and_id(self):
        project = create_project("Location Slug Project")

        location = create_hosting_location(project, data_type="Data Feed")

        self.assertEqual(location.slug, f"data-feed-{location.pk}")

    def test_hosting_location_slug_falls_back_to_resource_when_data_type_missing(self):
        project = create_project("Fallback Slug Project")

        location = create_hosting_location(project, data_type="")

        self.assertEqual(location.slug, f"resource-{location.pk}")

    def test_hosting_location_slug_preserved_when_explicit(self):
        project = create_project("Explicit Resource Slug")

        location = HostingLocation.objects.create(
            project=project,
            data_type="Dataset",
            slug="custom-resource-slug",
        )

        self.assertEqual(location.slug, "custom-resource-slug")

    def test_project_date_constraint_rejects_end_before_start(self):
        start_date = utc_datetime(2024, 7, 1)
        end_date = utc_datetime(2024, 1, 1)

        with self.assertRaises(IntegrityError):
            with transaction.atomic():
                create_project(
                    "Invalid Dates",
                    start_date=start_date,
                    end_date=end_date,
                )

    def test_hosting_location_product_type_through_model_is_unique(self):
        project = create_project("Unique Link Project")
        product_type = create_product_type("Unique Type")
        location = create_hosting_location(project)

        HostingLocationProductType.objects.create(
            hosting_location=location,
            product_type=product_type,
        )

        with self.assertRaises(IntegrityError):
            with transaction.atomic():
                HostingLocationProductType.objects.create(
                    hosting_location=location,
                    product_type=product_type,
                )

    def test_project_picture_upload_to_uses_project_id(self):
        project = create_project("Picture Upload Project")
        instance = type("PictureStub", (), {"project_id": project.id})()

        path = project_picture_upload_to(instance, "hero.jpg")

        self.assertEqual(
            path,
            f"projects_catalog/project_pictures/{project.id}/hero.jpg",
        )

    def test_project_picture_upload_to_uses_unassigned_when_project_missing(self):
        instance = type("PictureStub", (), {"project_id": None})()

        path = project_picture_upload_to(instance, "hero.jpg")

        self.assertEqual(path, "projects_catalog/project_pictures/unassigned/hero.jpg")
