"""
Django settings for CCRABDashboard project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
from ctypes.util import find_library
from datetime import timedelta
from pathlib import Path

import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure app packages at the repository root (e.g., projects_catalog) are importable
# even when Django is launched from a nested working directory.
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

env = environ.Env()
environ.Env.read_env(str(BASE_DIR / '.env'))


def _clean_env_list(raw_values):
    cleaned_values = []
    for raw_value in raw_values:
        cleaned_value = raw_value.strip()
        if cleaned_value:
            cleaned_values.append(cleaned_value)
    return cleaned_values


is_running_in_docker = env.bool("DJANGO_IN_DOCKER", default=Path("/.dockerenv").exists())
default_gdal_library_path = "/opt/homebrew/opt/gdal/lib/libgdal.dylib"
default_geos_library_path = "/opt/homebrew/opt/geos/lib/libgeos_c.dylib"
if is_running_in_docker:
    default_gdal_library_path = find_library("gdal")
    default_geos_library_path = find_library("geos_c")

gdal_library_path = env("GDAL_LIBRARY_PATH", default=default_gdal_library_path)
if gdal_library_path:
    GDAL_LIBRARY_PATH = gdal_library_path

geos_library_path = env("GEOS_LIBRARY_PATH", default=default_geos_library_path)
if geos_library_path:
    GEOS_LIBRARY_PATH = geos_library_path

# Shared asset locations:
# - MEDIA_ROOT stores user-uploaded files from all apps (app-specific subfolders via upload_to).
# - STATIC_ROOT is the collectstatic output directory.
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
default_secret_key = "django-insecure-ux7u)^woco3$_@atw=7b52dm@@xpd=79a5y-9ir)5rtu=panq4"
secret_key = env("DJANGO_SECRET_KEY", default=env("SECRET_KEY", default=default_secret_key))
if not secret_key or secret_key == "your-secret-key-here-change-in-production":
    SECRET_KEY = default_secret_key
else:
    SECRET_KEY = secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

raw_allowed_hosts = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "0.0.0.0"],
)
ALLOWED_HOSTS = _clean_env_list(raw_allowed_hosts)

raw_csrf_trusted_origins = env.list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default=[],
)
CSRF_TRUSTED_ORIGINS = _clean_env_list(raw_csrf_trusted_origins)

if env.bool("DJANGO_TRUST_X_FORWARDED_PROTO", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool("DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.gis",  # GeoDjango
    "rest_framework",
    "rest_framework_gis",
    "platforms_app.apps.PlatformsAppConfig",
    "projects_catalog.apps.ProjectsCatalogConfig",
    "corsheaders"
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",

]

ROOT_URLCONF = 'CCRABDashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'CCRABDashboard.context_processors.frontend_api_auth',
            ],
        },
    },
]

WSGI_APPLICATION = 'CCRABDashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": env("DATABASE_NAME"),
        "USER": env("DATABASE_USER"),
        "PASSWORD": env("DATABASE_PASSWORD"),
        "HOST": env("DATABASE_HOST"),
        "PORT": env("DATABASE_PORT"),
        "OPTIONS": {
            # Ensure Django creates / migrates in schema 'django' while still being able to read 'public'
            "options": "-c search_path=django,public"
        }

    }
}

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)
raw_cors_allowed_origins = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOWED_ORIGINS = _clean_env_list(raw_cors_allowed_origins)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "platforms_app": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}